// Code generated by MockGen. DO NOT EDIT.
// Source: dao.go

// Package dao is a generated GoMock package.
package dao

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/jphillips2121/movies-api/models"
	reflect "reflect"
)

// MockDAO is a mock of DAO interface
type MockDAO struct {
	ctrl     *gomock.Controller
	recorder *MockDAOMockRecorder
}

// MockDAOMockRecorder is the mock recorder for MockDAO
type MockDAOMockRecorder struct {
	mock *MockDAO
}

// NewMockDAO creates a new mock instance
func NewMockDAO(ctrl *gomock.Controller) *MockDAO {
	mock := &MockDAO{ctrl: ctrl}
	mock.recorder = &MockDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDAO) EXPECT() *MockDAOMockRecorder {
	return m.recorder
}

// GetJSONData mocks base method
func (m *MockDAO) GetJSONData() (*models.Movies, error) {
	ret := m.ctrl.Call(m, "GetJSONData")
	ret0, _ := ret[0].(*models.Movies)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJSONData indicates an expected call of GetJSONData
func (mr *MockDAOMockRecorder) GetJSONData() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONData", reflect.TypeOf((*MockDAO)(nil).GetJSONData))
}
